- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: Install the nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes

